Vagrant.configure("2") do |config|
  # Define the Ubuntu VM
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "generic/ubuntu2004"  # Use an Ubuntu box compatible with VirtualBox
    ubuntu.vm.network "private_network", type: "dhcp"  # DHCP for IP addressing
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = 1024  # Set the VM memory size
      vb.cpus = 2       # Set the number of CPU cores
    end
  end

  # Define the Alpine VM
  config.vm.define "alpine" do |alpine|
    alpine.vm.box = "generic/alpine316"  # Use an Alpine box compatible with VirtualBox
    alpine.vm.network "private_network", type: "dhcp"  # DHCP for IP addressing
    alpine.vm.provider "virtualbox" do |vb|
      vb.memory = 512   # Set the VM memory size
      vb.cpus = 1      # Set the number of CPU cores
    end
  end
end
