Vagrant.configure("2") do |config|
  
  # Define the Ubuntu VM
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "generic/ubuntu2004"  # Use an Ubuntu box compatible with libvirt
    ubuntu.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 1024  # Set the VM memory size
      libvirt.cpus = 2       # Set the number of CPU cores
    end
  end

  # Define the Alpine VM
  config.vm.define "alpine" do |alpine|
    alpine.vm.box = "generic/alpine316"  # Use an Alpine box compatible with libvirt
    alpine.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 512  # Set the VM memory size
      libvirt.cpus = 1      # Set the number of CPU cores
    end
  end
end
