Vagrant.configure("2") do |config|
  # Create an Ubuntu VM
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.network "private_network", type: "dhcp"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # Create an Alpine VM
  config.vm.define "alpine" do |alpine|
    alpine.vm.box = "generic/alpine316"
    alpine.vm.network "private_network", type: "dhcp"
    alpine.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
end
