# DeepSource configuration file
# Learn how to configure: https://docs.deepsource.com/docs/configuration
version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "ruff"